{% set name = "pymonetdb" %}
{% set version = "1.8.3" %}
{% set sha256 = "0ff2a2eab7143c3d65f32abb1538e43b9d5a8b1d60a5916e4538a7540a3544ce" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/gijzelaerr/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - future
    - python >={{ python_min }}
    - setuptools

test:
  requires:
    - python {{ python_min }}
  imports:
    - pymonetdb
    - pymonetdb.sql

about:
  home: http://www.monetdb.org
  license: MPL-2.0
  license_family: OTHER
  license_file: LICENSE
  summary: The Python API for MonetDB
  dev_url: https://github.com/gijzelaerr/pymonetdb
  description: |
    pymonetdb is a native python client API for monetDB. This API is 
    cross-platform, and doesn't depend on any monetdb libraries. It has
    support for python 2.7, Python 3 and PyPy. The driver is also Python
    DBAPI 2.0 compatible.

extra:
  recipe-maintainers:
    - igortg
    - nicoddemus
