{% set name = "pymonetdb" %}
{% set version = "1.2.1" %}
{% set sha256 = "df1d6ee32e74359b1fa90e73c3bc54d1468bb159d8cefb2e378fcb35e4e7d3ed" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/gijzelaerr/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - pytest-runner
    - setuptools
  run:
    - python
    - six
    - setuptools

test:
  imports:
    - pymonetdb
    - pymonetdb.sql

about:
  home: http://www.monetdb.org
  license: MPL-2.0
  license_family: OTHER
  license_file: LICENSE
  summary: 'The Python API for MonetDB'
  description: |
    pymonetdb is a native python client API for monetDB. This API is 
    cross-platform, and doesn't depend on any monetdb libraries. It has
    support for python 2.7, Python 3 and PyPy. The driver is also Python
    DBAPI 2.0 compatible.

extra:
  recipe-maintainers:
    - igortg
    - nicoddemus
