{% set name = "pymonetdb" %}
{% set version = "1.7.0" %}
{% set sha256 = "55ffc4057e066d97b3ea1804f372a4b76287506799deac6a17e1e686a047250f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/gijzelaerr/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - future
    - python >=3.7
    - setuptools

test:
  imports:
    - pymonetdb
    - pymonetdb.sql

about:
  home: http://www.monetdb.org
  license: MPL-2.0
  license_family: OTHER
  license_file: LICENSE
  summary: The Python API for MonetDB
  dev_url: https://github.com/gijzelaerr/pymonetdb
  description: |
    pymonetdb is a native python client API for monetDB. This API is 
    cross-platform, and doesn't depend on any monetdb libraries. It has
    support for python 2.7, Python 3 and PyPy. The driver is also Python
    DBAPI 2.0 compatible.

extra:
  recipe-maintainers:
    - igortg
    - nicoddemus
