travis:
  secure:
    BINSTAR_TOKEN: hu43usnX/f93sDfR369popWbgGfjbrH0AwIXsWwe8Cgq6Zqw5P4K3woffsVBQM08RnFi3DRpWgRtFwNmLmj+wpS0FSx8CSLowdUIJptmvSrDYvS0L0s/s2o95bjpnWoK1ZLPWi5epP9Jy/ExRAOM0gmRm5VuBttGNOmK1Gw0jUFGucxGFYke+PaS6aaLBptyX14xsat6i3Fm26i4VO7SDXM7UyMqI8GFHQs5x+y8o057luzvvSbFumbffJMkTh4v1D1carpdGNPZRZM0xG+h9FZrrPfNSonCKgqeYezS3UjCnvBpuqVKafc/goGPpMOI6nwdyQ42ufo/tuB3DPBq/OFV8wc63oZCd2Ka30C2mSe2TgPF9boE8vpv01Etzxr2GwXGDYEcFPRSEwK2m1Xsp0OmkY+DEBjl3LvqTgbEjzicnry9YiPpWTbJ+uJNn2FHN6JgRV2A4hKT8EoExumvzwjcav2kQuR8l4CIupNOT4YucWyc0Wnfxz9AiVNWcyeWYTuCzKPth9Efi0u1GU54hMoYhFZC6UrrdMm3xMqYI1c2/vw97P5rTbgEr26Ls8DB9tN8WK9hfKfpns6kE7rZlrpc2srr/OAhYIyvSWI1y5MKXwbcJFvej4BwHexqXzOTzeXt7UXSWpGnd+U4cx80x40UN7F9ZpN0muvi2r6Hmz0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
