travis:
  secure:
    BINSTAR_TOKEN: qNmFR56C2LSGUCOGlhDUjR0rGrkFwEhYnfhI8SJOMHRI5vM79uUvDzOnMv8LTB6GApVjhfQ41Jod7HrcQ/2/MMxcgsUw+qf4AWJis04bsiy5jAbTrrUqTX+mwxU8Hw6BF30ZxbjAPhsNE30VuqQIPLwEqY4B1qDcJn+kWIgUcM7CjTSqdhSrKAJBZTYfPJVX1Cppo0i0qIFUY7f4zozp8ciebHGnECPBYBwUveIPyuIaY88zg5awN7L7KrX82AAk/Do24UhGOMjzTUmvJcVFAFaYCcukG3KXgjEtlleF18zT+UGb9gJp9chdT/zfletsd46tRrrRr8U0CcZB1rBkIEHLtAPB4cm3qHCO9YCKVvCY0lV3x3LHIewuCLSYWhAWA17/hosOap13kFLa00/TNvkxkZwl7ba5+LqRxKB9FeoLAVPnLzmz3J8Mjgu9rzsMF+F6DiPiGF0fGV5DgShI5YSwC3kQErgTwpGMz68GaO94ZCc69fQY0Uc8P8LNlvAqFOB7NjPs4KWhFl0H5GVvEjSgXWQQnQtGxOwABO8u5yFc6e6Bngq5E8TYXUc6Knj8A3WKX6sk/NzwQLhLUqzMGfCerR/ZS5BF6jsjyC/vJltZLdJZZt+KJmZdbWWHTv1O1LKtQ74XVrVSUBsxhiSty4HMFASRr1zAKKaP6F3DKuE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
